"""_001_initial_migration

Revision ID: c8887276adf9
Revises:
Create Date: 2025-02-22 15:35:07.848288

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8887276adf9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geolocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=True),
        sa.Column("continent_code", sa.String(), nullable=False),
        sa.Column("continent_name", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("country_name", sa.String(), nullable=False),
        sa.Column("region_code", sa.String(), nullable=False),
        sa.Column("region_name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("zip", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_geolocations_address"), "geolocations", ["address"], unique=False)
    op.create_index(op.f("ix_geolocations_ip"), "geolocations", ["ip"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geolocations_ip"), table_name="geolocations")
    op.drop_index(op.f("ix_geolocations_address"), table_name="geolocations")
    op.drop_table("geolocations")
    # ### end Alembic commands ###
